apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline-application
  name: pipeline-application
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline-application
  template:
    metadata:
      labels:
        app: pipeline-application
    spec:
      containers:
      - image: dellintosh/pipeline-application
        name: pipeline-application
        ports:
        - containerPort: 80
          name: http
          protocol: TCP