apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: <<PROJECT_NAME>>
  name: <<PROJECT_NAME>>
  namespace: default
spec:
  selector:
    matchLabels:
      app: <<PROJECT_NAME>>
  template:
    metadata:
      labels:
        app: <<PROJECT_NAME>>
    spec:
      containers:
      - image: 277866474112.dkr.ecr.us-east-1.amazonaws.com/<<PROJECT_NAME>>
        name: <<PROJECT_NAME>>
        ports:
        - containerPort: 80
          name: http
          protocol: TCP