kind: Service
apiVersion: v1
metadata:
  name: pipeline-application
  namespace: default
spec:
  selector:
    app: pipeline-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer